### ISSUE TITLE
Data for Investigator during K-Axis

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDataCentre/raadsync#9]
See details here: http://soki.aq/display/researchcomm/Requirements+-+Investigator+leg

Note that the approach used by "asosi" could be used here for the BOM sources: 

https://github.com/mdsumner/asosi

Preferably do the georef with .vrt at download time with a special raadsync handler.

**Comment by mdsumner** [comment]
Note that the approach used by "asosi" could be used here:

**Comment by raymondben** [comment]
Those chart images can be obtained directly, e.g. for winds:
http://www.bom.gov.au/charts_data/IDY20001/current/windarrow/10m/IDY20001.windarrow-10m.000.png?1449576000

The digits on the end are seconds since Jan-1 1970. The 000 seems to be the forecast time. Wind data are also available for the full southern hemisphere. Waves are not, because they come from the AusWave model.

**Comment by raymondben** [comment]
Decided not to make this part of raadsync for now: for the purposes of the KAxis voyage Mike will cook up a standalone solution.
